config/routes.rb
Rails.application.routes.draw do
  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  root to: 'welcome#index'
  get "faq", to: "welcome#faq"
  get "about", to: "welcome#about"
  
  resources :meetings, only:[:index, :show]
  
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete 'logout', to: 'sessions#destroy', as: "logout"

  namespace :mobile do
    resources :search, only:[:new, :create, :index] do
      collection do
        get 'results', to: "search#new"
        get 'here-and-now', to: "search#here_and_now"
        get 'get-new-options', to: "search#get_new_options"
        post 'free_search', to: "search#free_search"
      end
    end

    # are these used?
    get "search/create", to: "search#create"
    resources :meetings, only:[:index, :show]
    ####
  end

namespace :admin do
    root to: "dashboards#index", as: "dashboard"
    resources :meetings, only:[:index, :edit, :update]
    resources :users, only:[:index]
  end

  get '403', to: 'error#unauthorized', as: "unauthorized"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def faq
    params[:expand] = params[:expand].presence
  end

  def about
    
  end
end

app/views/welcome/about.html.haml
.container-fluid.welcome-header
  .col-sm-2
  .col-sm-8
    .row.header-text
      %h1.text-left About
    %p
      Thank you for visiting Denver Meetings! This site is the realization of a years-old dream to list Alcohlics Anonymous meetings in metro Denver in a user-friendly format. While the information on daccaa.org is great, the creator of this site and many others found AA meeting listings difficult to find.
    %p
      The biggest pain points we are trying to address are finding meetings from a mobile device, and finding meetings relative to a location. It is a work in progress, but we hope that you already find it to be of use! Please provide any feedback or just drop a note to say hello #{mail_to "admin@denvermeetings.org", "here"}.
    %p
      Disclaimer: This site is not affiliated with Alcoholics Anonymous, Denver Area Central Committee of Alcoholics Anonymous (daccaa.org) or any 12-step group. These listings are provided as a service only. No warranty is given or implied. Information found here is provided "as is" and is not intended to diagnose, prevent, or treat any disease.
    %p
      If you have a drinking problem, there is help. But you may have to take some action. Welcome!
  .col-sm-2

app/views/welcome/faq.html.haml
.container-fluid.welcome-header
  .col-sm-2
  .col-sm-8
    .row.header-text
      %h1.text-left FAQ
    .row.meeting-button-row
      #accordion.panel-group
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
                Is this an AA site?
          #collapseOne.panel-collapse.collapse
            .panel-body
              No, this site is not affiliated with Alcoholics Anonymous or any 12-step group. This site is not affiliated with Denver Area Central Committee of Alcoholics Anonymous or daccaa.org. These listings are provided as a service only. No warranty is given or implied. Information found here is provided "as is" and is not intended to diagnose, prevent, or treat any disease.
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseFive"}
                Can you do a site for my city/organization?
          #collapseFive.panel-collapse.collapse
            .panel-body
              The creator of this site is employed full time and maintains this site as an avocation. You may contact them at #{mail_to "admin@denvermeetings.org", "admin@denvermeetings.org"}.
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a#can-i-attend{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseSix"}
                I'm not an alcoholic. Can I attend an AA meeting?
          #collapseSix.panel-collapse.collapse
            .panel-body
              Meetings designated as "open" are generally open to anyone. Some open meetings may welcome anyone but restrict sharing to those with a desire to stop drinking. It may be wise to show up a few minutes early to a meeting you are unsure about. Otherwise, a meeting's "format" (the text read by the chairperson) should clarify who may attend/participate in the meeting.
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a#open-closed{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseSeven"}
                What's an open meeting? What's a closed meeting?
          #collapseSeven.panel-collapse.collapse
            .panel-body
              Meetings designated as closed are for people with a desire to stop drinking, and only for people with a desire to stop drinking. Sometimes this is interpreted by groups as the necessity to admit you are an alcoholic in order to attend. Meetings designated as "open" are generally open to anyone, although some may restrict sharing to those with a desire to stop drinking.
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseEight"}
                This information is incorrect. Can you fix it?
          #collapseEight.panel-collapse.collapse
            .panel-body
              That is frustrating and we apologize for any inconvenience. The best thing to do would be to check the listing on #{link_to "Denver AA's site", "http://www.daccaa.org/meetings.htm"}. If the information is correct there and incorrect on this site, #{mail_to "admin@denvermeetings.org", "please let us know"}. If the information with Denver AA is incorrect, please update them, and this site will be updated automatically. As a reminder, this site is not affiliated with AA at any level.
  .col-sm-2
= javascript_tag do
  $(document).ready(function() {
  var expand = $( "##{params[:expand]}" );
  if (expand.length) { expand.click(); }
  });
  

app/views/welcome/index.html.haml
.container-fluid.welcome-header
  .col-sm-2
  .col-sm-8
    .row.meeting-button-row
      = link_to "Find an AA Meeting >", new_mobile_search_path, { class: "btn btn-lg btn-default center-block find-meetings-button", id: "meetings-button" }
      = link_to "Upcoming Nearby Meetings >", '', { class: "btn btn-lg btn-default center-block find-meetings-button", id: "big-here-button" }
  .col-sm-2

:javascript
  function geoSuccess(position){
    var pos = {
      "lat": position.coords.latitude,
      "lng": position.coords.longitude
    };
    upcomingSubmit(pos);
  }

  function apiLocateSuccess(position){
    var pos = {
      "lat": position.location.lat,
      "lng": position.location.lng
    }
    upcomingSubmit(pos);
  }

  function geoFailure(){
    alert("Geolocation cancelled or errored: using Denver city center");
      var pos = {
        "lat": "",
        "lng": ""
      };
    upcomingSubmit(pos);
  }

  function upcomingSubmit(pos){
    var createUrl = '#{here_and_now_mobile_search_index_path(
     lat: "__LAT__", lng: "__LNG__", format: :html)}';
    createUrl = createUrl.replace("__LAT__", pos["lat"]).replace("__LNG__", pos["lng"]);

    window.location = createUrl;
    return false;
  }

  function apiGeoLocate() {
    var url = 'https://www.googleapis.com/geolocation/v1/geolocate?key=' +
      "#{ENV['google_api_key_client']}";
    $.post(url, apiLocateSuccess)
     .fail(geoFailure);
  }

  $(document).ready( function(){
    $("#big-here-button").click(function(e){
      e.preventDefault();
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(geoSuccess, apiGeoLocate);
        return false;
      } else { apiGeoLocate(); }
    });
  }() );