config/routes.rb
Rails.application.routes.draw do
  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  root to: 'welcome#index'
  get "faq", to: "welcome#faq"
  get "about", to: "welcome#about"
  
  resources :meetings, only:[:index, :show]
  
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete 'logout', to: 'sessions#destroy', as: "logout"

  namespace :mobile do
    resources :search, only:[:new, :create, :index] do
      collection do
        get 'results', to: "search#new"
        get 'here-and-now', to: "search#here_and_now"
        get 'get-new-options', to: "search#get_new_options"
        post 'free_search', to: "search#free_search"
      end
    end

    # are these used?
    get "search/create", to: "search#create"
    resources :meetings, only:[:index, :show]
    ####
  end

namespace :admin do
    root to: "dashboards#index", as: "dashboard"
    resources :meetings, only:[:index, :edit, :update]
    resources :users, only:[:index]
  end

  get '403', to: 'error#unauthorized', as: "unauthorized"

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < AdminController
  def index
  end
end

app/views/admin/dashboards/index.html.erb
<div class="container container-fluid dashboard--main">
  <div class="row">
    <%= link_to "Manage Meetings", admin_meetings_path, class: "btn btn-success" %>
  </div>
  <div class="row">
    <%= link_to "Manage Users", admin_users_path, class: "btn btn-success" %>
  </div>
</div>

<style>
  .dashboard--main {
    margin-top: 5em;
  }

  .dashboard--main .row {
    margin-bottom: 1em;
  }
</style>