config/routes.rb
Rails.application.routes.draw do
  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  root to: 'welcome#index'
  get "faq", to: "welcome#faq"
  get "about", to: "welcome#about"
  
  resources :meetings, only:[:index, :show]
  
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete 'logout', to: 'sessions#destroy', as: "logout"

  namespace :mobile do
    resources :search, only:[:new, :create, :index] do
      collection do
        get 'results', to: "search#new"
        get 'here-and-now', to: "search#here_and_now"
        get 'get-new-options', to: "search#get_new_options"
        post 'free_search', to: "search#free_search"
      end
    end

    # are these used?
    get "search/create", to: "search#create"
    resources :meetings, only:[:index, :show]
    ####
  end

namespace :admin do
    root to: "dashboards#index", as: "dashboard"
    resources :meetings, only:[:index, :edit, :update]
    resources :users, only:[:index]
  end

  get '403', to: 'error#unauthorized', as: "unauthorized"

end

app/views/layouts/_flash.html.haml
- if flash.to_a.length > 0
  .alert-container
- flash.each do |type, message|
  %div{:class => "alert alert-#{type}", :role => "alert"}
    = raw(message)
    

app/views/layouts/_footer.html.haml
%footer.footer.container-fluid
  .row.center-block
    .col-lg-2
    #copyright.col-lg-8
      %p.text-center
        = link_to "Admin", login_path, { class: "admin-link" }
    .col-lg-2

app/views/layouts/_navbar.html.haml
/ Fixed navbar
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Denver AA Meetings", root_path, { class: "navbar-brand" }
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "About", about_path
        %li= link_to "FAQ", faq_path
        %li= mail_to "admin@denvermeetings.org", "Contact"
    / /.nav-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title DenverMeetings
    %meta{:content => "initial-scale = 1.0,maximum-scale = 1.0", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      = render partial: 'layouts/navbar'
      = render partial: 'layouts/flash'
      = yield
      = render partial: 'layouts/footer'

- if Rails.env.production?
  = javascript_include_tag 'shared/analytics_init.js'

app/views/layouts/mobile.html.haml
!!!
%html
  %head
    %title DenverMeetings
    %meta{:content => "initial-scale = 1.0,maximum-scale = 1.0", :name => "viewport"}/
    = stylesheet_link_tag 'mobile/mobile', media: 'all'
    = javascript_include_tag 'mobile/mobile', media: 'all'
    = csrf_meta_tags
  %body
    #p1{"data-role" => "page", "data-theme" => "b"}
      = yield

- if Rails.env.production?
  = javascript_include_tag 'shared/analytics_init.js'